# Generated by Django 3.2.10 on 2021-12-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0002_auto_20211222_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolUpload',
            new_name='SchoolUploadError',
        ),
    ]
