# Generated by Django 3.2.10 on 2021-12-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0004_alter_schooluploaderror_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='outcome',
            field=models.CharField(default='Processing incomplete', max_length=400),
        ),
    ]
