# Generated by Django 3.2.10 on 2021-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('urn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('open_date', models.DateField(blank=True)),
                ('close_date', models.DateField(blank=True)),
                ('town', models.CharField(blank=True, max_length=150)),
                ('postcode', models.CharField(blank=True, max_length=7)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
