# Generated by Django 3.2.10 on 2021-12-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='status',
            new_name='open',
        ),
    ]
