# Generated by Django 3.2.10 on 2021-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_status_school_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
